---
spring:
  application:
    name: "kapita"
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:}"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kapita-db}"
    username: "${DB_USER:kapita}"
    password: "${DB_PASSWORD:change-me}"
  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
    consumer:
      group-id: "${KAFKA_CONSUMER_GROUP_ID:kapita-service}"
    listener:
      missing-topics-fatal: false
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      eclipselink.weaving: "false"
      eclipselink.ddl-generation: "none"
      eclipselink.target-database: "PostgreSQL"
      eclipselink.logging.level: "WARNING"
      eclipselink.logging.level.sql: "FINE"
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"
kapita:
  messaging:
    user-created:
      topic: "${KAPITA_USER_CREATED_TOPIC:user-created}"
  security:
    jwt:
      issuer: "${ISSUER_URI:http://localhost:8080/realms/kapital-financial}"
      audience: "${JWT_AUDIENCE:kapita-api}"
      public-key-location: "classpath:security/jwt-public.pem"
logging:
  level:
    org.springframework.security: "INFO"
    org.springframework.web: "INFO"
